/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppProfiloRouteImport } from './routes/_authenticated/app.profilo'
import { Route as AuthenticatedAppListeRouteImport } from './routes/_authenticated/app.liste'
import { Route as AuthenticatedAppAmiciRouteImport } from './routes/_authenticated/app.amici'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as AuthenticatedAppListeListIdRouteImport } from './routes/_authenticated/app.liste.$listId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppProfiloRoute = AuthenticatedAppProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppListeRoute = AuthenticatedAppListeRouteImport.update({
  id: '/liste',
  path: '/liste',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAmiciRoute = AuthenticatedAppAmiciRouteImport.update({
  id: '/amici',
  path: '/amici',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppListeListIdRoute =
  AuthenticatedAppListeListIdRouteImport.update({
    id: '/$listId',
    path: '/$listId',
    getParentRoute: () => AuthenticatedAppListeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/amici': typeof AuthenticatedAppAmiciRoute
  '/app/liste': typeof AuthenticatedAppListeRouteWithChildren
  '/app/profilo': typeof AuthenticatedAppProfiloRoute
  '/app/liste/$listId': typeof AuthenticatedAppListeListIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/amici': typeof AuthenticatedAppAmiciRoute
  '/app/liste': typeof AuthenticatedAppListeRouteWithChildren
  '/app/profilo': typeof AuthenticatedAppProfiloRoute
  '/app/liste/$listId': typeof AuthenticatedAppListeListIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/amici': typeof AuthenticatedAppAmiciRoute
  '/_authenticated/app/liste': typeof AuthenticatedAppListeRouteWithChildren
  '/_authenticated/app/profilo': typeof AuthenticatedAppProfiloRoute
  '/_authenticated/app/liste/$listId': typeof AuthenticatedAppListeListIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/amici'
    | '/app/liste'
    | '/app/profilo'
    | '/app/liste/$listId'
    | '/api/public/hooks/send-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/app/amici'
    | '/app/liste'
    | '/app/profilo'
    | '/app/liste/$listId'
    | '/api/public/hooks/send-reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/amici'
    | '/_authenticated/app/liste'
    | '/_authenticated/app/profilo'
    | '/_authenticated/app/liste/$listId'
    | '/api/public/hooks/send-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/profilo': {
      id: '/_authenticated/app/profilo'
      path: '/profilo'
      fullPath: '/app/profilo'
      preLoaderRoute: typeof AuthenticatedAppProfiloRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/liste': {
      id: '/_authenticated/app/liste'
      path: '/liste'
      fullPath: '/app/liste'
      preLoaderRoute: typeof AuthenticatedAppListeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/amici': {
      id: '/_authenticated/app/amici'
      path: '/amici'
      fullPath: '/app/amici'
      preLoaderRoute: typeof AuthenticatedAppAmiciRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/liste/$listId': {
      id: '/_authenticated/app/liste/$listId'
      path: '/$listId'
      fullPath: '/app/liste/$listId'
      preLoaderRoute: typeof AuthenticatedAppListeListIdRouteImport
      parentRoute: typeof AuthenticatedAppListeRoute
    }
  }
}

interface AuthenticatedAppListeRouteChildren {
  AuthenticatedAppListeListIdRoute: typeof AuthenticatedAppListeListIdRoute
}

const AuthenticatedAppListeRouteChildren: AuthenticatedAppListeRouteChildren = {
  AuthenticatedAppListeListIdRoute: AuthenticatedAppListeListIdRoute,
}

const AuthenticatedAppListeRouteWithChildren =
  AuthenticatedAppListeRoute._addFileChildren(
    AuthenticatedAppListeRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAmiciRoute: typeof AuthenticatedAppAmiciRoute
  AuthenticatedAppListeRoute: typeof AuthenticatedAppListeRouteWithChildren
  AuthenticatedAppProfiloRoute: typeof AuthenticatedAppProfiloRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAmiciRoute: AuthenticatedAppAmiciRoute,
  AuthenticatedAppListeRoute: AuthenticatedAppListeRouteWithChildren,
  AuthenticatedAppProfiloRoute: AuthenticatedAppProfiloRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
